name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest 
            artifact_name: shmanga
            asset_name: shmanga-linux-amd64
          - os: windows-latest
            artifact_name: shmanga.exe
            asset_name: shmanga-windows-amd64.exe
          - os: macos-latest
            artifact_name: shmanga
            asset_name: shmanga-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go on ${{ matrix.os }}
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18.2"
      - name: Build on ${{ matrix.os }}
        run: go build
      - name: Rename file
        run: mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}
      - name: Upload ${{ matrix.asset_name }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}